/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.engineup;

import javax.swing.JTextArea;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author SCHOOL
 */
public class EngineUp extends javax.swing.JFrame {

    /**
     * Creates new form EngineUp
     */
    public EngineUp() {
        initComponents();
        
        DefaultCaret caret = (DefaultCaret)outputTextArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnSearchSample = new javax.swing.JButton();
        btnBackupDb = new javax.swing.JButton();
        btnInstallDb = new javax.swing.JButton();
        btnRestoreDb = new javax.swing.JButton();
        btnCheckHealth = new javax.swing.JButton();
        btnOpenTypesenseClient = new javax.swing.JButton();
        chkPortForward = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName(""); // NOI18N

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        outputTextArea.setName("outputTextArea"); // NOI18N
        jScrollPane1.setViewportView(outputTextArea);

        jPanel1.setMaximumSize(new java.awt.Dimension(300, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        btnSearchSample.setLabel("Search Sample");
        btnSearchSample.setMaximumSize(new java.awt.Dimension(10000, 25));
        jPanel1.add(btnSearchSample);

        btnBackupDb.setText("Backup DB (PF)");
        btnBackupDb.setMaximumSize(new java.awt.Dimension(10000, 25));
        jPanel1.add(btnBackupDb);

        btnInstallDb.setText("Install Typesense");
        btnInstallDb.setMaximumSize(new java.awt.Dimension(10000, 25));
        btnInstallDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallDbActionPerformed(evt);
            }
        });
        jPanel1.add(btnInstallDb);

        btnRestoreDb.setText("Restore DB");
        btnRestoreDb.setMaximumSize(new java.awt.Dimension(10000, 25));
        jPanel1.add(btnRestoreDb);

        btnCheckHealth.setText("Check Health (PF)");
        btnCheckHealth.setMaximumSize(new java.awt.Dimension(10000, 25));
        btnCheckHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckHealthActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckHealth);

        btnOpenTypesenseClient.setText("Open Typesense client (PF)");
        btnOpenTypesenseClient.setMaximumSize(new java.awt.Dimension(10000, 25));
        btnOpenTypesenseClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenTypesenseClientActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenTypesenseClient);

        chkPortForward.setLabel("Enable Port Forward");
        chkPortForward.setMaximumSize(new java.awt.Dimension(1000, 25));
        jPanel1.add(chkPortForward);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckHealthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckHealthActionPerformed

    private void btnOpenTypesenseClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenTypesenseClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenTypesenseClientActionPerformed

    private void btnInstallDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallDbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInstallDbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EngineUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EngineUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EngineUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EngineUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EngineUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBackupDb;
    public javax.swing.JButton btnCheckHealth;
    public javax.swing.JButton btnInstallDb;
    public javax.swing.JButton btnOpenTypesenseClient;
    public javax.swing.JButton btnRestoreDb;
    public javax.swing.JButton btnSearchSample;
    public javax.swing.JCheckBox chkPortForward;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputTextArea;
    // End of variables declaration//GEN-END:variables

    public JTextArea getOutputTextArea() {
        return outputTextArea;
    }
}
