---
apiVersion: v1
kind: Namespace
metadata:
  name: typesense
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: typesense-data-pv
  namespace: typesense
  labels:
    type: local
spec:
  storageClassName: "gp3"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rancher"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typesense-data-pvc
  namespace: typesense
spec:
  storageClassName: "gp3"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: local
---
apiVersion: v1
kind: Pod
metadata:
  name: typesense-agent-ssh
  namespace: typesense
  labels:
    app: typesense-agent-ssh
spec:
  containers:
    - name: alpine-ssh
      image: sickp/alpine-sshd:7.9-r1
      ports:
        - containerPort: 22
      volumeMounts:
        - name: typesense-data
          mountPath: /data
  volumes:
    - name: typesense-data
      persistentVolumeClaim:
        claimName: typesense-data-pvc